### ISSUE TITLE
Unable to get rid of old entries

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-website#42]
[Hope this is not duplicated]

The name "Agbetunsin" (http://yorubaname.com/entries/agbetunsin) was part of the first batch of names in the dictionary, perhaps obtained through Excel uploading. But now after I've edited the entry and republished it with the proper tone marks (http://yorubaname.com/entries/A%CC%80gbe%CC%81tu%CC%81nsi%CC%80n), I see that the two entries are still showing on the dictionary instead of the latest one.

Now, when the user searches, unfortunately, they are taken to the old version and not the newer one. How can we delete the old one. More importantly, how can we make sure that when an entry (taken from uploaded entries, or not) is edited, the edited form replaces the old one?

**Comment by kolatubosun** [comment]
Same for [old Ajibawo](http://yorubaname.com/entries/ajibawo) and [new Ajibáwo](http://yorubaname.com/entries/Aji%CC%81ba%CC%81wo)

**Comment by temiyemi** [comment]
I noticed this has to do with tonal marks and the autocomplete / search functionality. I'd suggest we have an additional field in the name entries, for alternative spellings of names (i.e. without tonal marks). @dadepo do you think that would help?

**Comment by kolatubosun** [comment]
Okay. Makes sense.

In that case then, what I suggest (I've thought about this before) is that the main field for each entry be without tone marks. i.e. the name that shows up when user searches for it on the homepage be totally plain. It also helps since most people don't even query with tone marks anyway.

So when the user enters the full entry page after pressing "enter", then they'd see the properly tone-marked version (perhaps as the second field. Or if by then we can make the toneless one invisible, they'd only now see the proper tone mark. The point is that whenever they're in the full entry mode, they're able to see the tone marks on the name).

The advantage of doing it this way is that it will also help deal with ambiguities that I've talked about in the issues about homographs. e.g. a name like Adésọ́lá and Adéṣọlá can be grouped under one entry called "Adesola" with no tone marking. And when the user gets in, then he sees the two tonal distinctions, and the different meanings for each of them.

**Comment by temiyemi** [comment]
That’s what I was thinking too. We could then list all names with the same spelling, but different tonal marks and meanings.

With this, we can ditch the on-screen keyboard used for tonal entry, perhaps till we can improve the UX for tonal marks entry.

**Comment by kolatubosun** [comment]
Actually, the on-screen keyboard has been useless so far, more so since we already have a downloadable keyboard for people to use. In my experience, and for UX, most people just want to type in a name without bothering with tone marks. But they want to know the correct tone marking. 

So this will be a good solution. It will also solve the problem with the URL. The tone marking has currently made it hard to have a plain URL like yorubaname.com/entries/sangodare. What we see is something like http://yorubaname.com/entries/%E1%B9%A2a%CC%80ngo%CC%81da%CC%81re which creates problems when tweeted (See Issue #32).

How soon can it be implemented?

**Comment by dadepo** [comment]
"I noticed this has to do with tonal marks and the autocomplete / search functionality. I'd suggest we have an additional field in the name entries, for alternative spellings of names (i.e. without tonal marks). @dadepo do you think that would help?"
I just did a quick look into this issue and it is way more than "tonal marks and the autocomplete / search functionality". There is definitely something massively wrong with the flow of updating a name. I was able to replicate the original issue and the problem seems to be when a name is edited, and then it is published, it is published as a new entry (instead of updating the entry). This is wrong and we should fix this. (If I remember correctly i think it will have something to do with the business rule that a name is unique...so when it is changed (by being updated) it is effectively creating a new entry in the search index.

I will read through the discussions about the tonal mark later, but as far as I can tell that is totally a different issue and it won't fix the original problem reported here.

**Comment by kolatubosun** [comment]
One more problem here, which migh also have been duplicated elsewhere. Some names which are in the dictionary are being returned as not being there. An example is "Ọlá" which I just successfully added after a long trial and error. It's listed on the homepage as a new addition, but when you search for it, or click on it, you get an error. See photos.
![screenshot 511](https://user-images.githubusercontent.com/18510601/32175537-8f74f49e-bd85-11e7-88af-42d7c66bf7a6.png)
![screenshot 510](https://user-images.githubusercontent.com/18510601/32175538-8fb05b42-bd85-11e7-8c00-5a756ad54ccc.png)
