### ISSUE TITLE
Make the onscreen keyboard actually usable

### ISSUE THREAD

**Issue by dadepo** [Yorubaname/yorubaname-website#49]
Currently the onscreen keyboard is actually not usable. This is because once you click anywhere on the page, whatever has been typed using the onscreen keyboard get cleared. This should be fixed. 

Other improvements that might be needed include:

1. If a user clicks on the keyboard icon when the onscreen keyboard is already open, then close the onscreen keyboard, instead of reopening it again.
2. The tool tip "click here for keys with accent" which shows when a user hovers on the keyboard icon should be styled to be more legible.

**Comment by kolatubosun** [comment]
Do you think we should remove the onscreen keyboard totally since everyone enters a name without tone marks and we're already considering making that the default mode of query? Personally, I think downloading the tone-marking software is more efficient than the on-screen keyboard that is harder and slower to use (and now, in the future, useless).

**Comment by dadepo** [comment]
Yup...I agree with you. Never really had faith in the UX of any onscreen keyboard. Wanted to give it a second chance by at-least making it work before we conclude that people are not using it, since it was never really usable from the get go...but perhaps that is not worth the effort. So closing this issue. Created another one for the onscreen keyboard to be removed here #49
