### ISSUE TITLE
Improve search result via Google

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-website#59]
When someone types ANY Yoruba name into Google, how can we make sure that the first (or some of the first) result of the search takes them to Yorubaname.com?

**Comment by Flipponachi** [comment]
On that I think the issue is seeing that Google algorithm works straight of English language and entries on the site aren't straight up English but rather diacritics words, the user is always directed to other sites, what I think might be helpful is to have both? Am open to suggestions, cos I like a good challenge

**Comment by kolatubosun** [comment]
What of when someone just asks "what is the meaning of X name?", can we make it point to us as a default?

**Comment by Zifah** [comment]
@kolatubosun is this still relevant? Based on a few quick tests, the website ranks quite highly for such searches like "what is the meaning of X" now.

**Comment by kolatubosun** [comment]
Yea, we can close this.

**Comment by Zifah** [comment]
Closed based on previous discussions.
